---
- name: Converge
  hosts: all
  tasks:
    - name: install requirements
      apt:
        name: gnupg
        state: present
        update_cache: yes
    - name: "Include 1mr.zabbix_agent2"
      include_role:
        name: "1mr.zabbix_agent2"
