---
name: Molecule Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - buster
          - bullseye
    container:
      image: 1am3r/debian:molecule-${{ matrix.distro }}
    env:
      ANSIBLE_CALLBACK_WHITELIST: profile_tasks
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yamllint ansible-lint flake8 'molecule[docker]' docker
      - name: Test with molecule
        run: |
          molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
